In [1]:
# import dependencies
import pandas as pd

In [6]:
# read in data
pd.set_option('display.max_columns', None)
mlb_df = pd.read_csv('resources/mlb_data.csv')
mlb_df.head()

Year-Tm  Year   Tm  Lg   W-L%  R/G-hit  HR-hit  RBI-hit  SB-hit  BB-hit  \
0  2019MIN  2019  MIN  AL  0.623     5.80     307      906      28     525   
1  2019NYY  2019  NYY  AL  0.636     5.82     306      904      55     569   
2  2019HOU  2019  HOU  AL  0.660     5.68     288      891      67     645   
3  2019LAD  2019  LAD  NL  0.654     5.47     279      861      57     607   
4  2018NYY  2018  NYY  AL  0.617     5.25     267      821      63     625   

   SO-hit  BA-hit  OBP-hit  SLG-hit  OPS-hit  LOB-hit  OPS+-hit  ERA-pitch  \
0    1334   0.270    0.338    0.494    0.832     1115       119       4.18   
1    1437   0.267    0.339    0.490    0.829     1039       117       4.31   
2    1166   0.274    0.352    0.495    0.848     1168       120       3.66   
3    1356   0.257    0.338    0.472    0.810     1124       112       3.39   
4    1421   0.249    0.329    0.451    0.781     1100       112       3.78   

   WHIP-pitch  H9-pitch  HR9-pitch  SO/W-pitch  ERA+-pitch  Winner  
0       1.304       9.0        1.2        3.24         108   False  
1       1.304       8.6        1.5        3.03         106   False  
2       1.130       7.4        1.4        3.73         127   False  
3       1.102       7.5        1.2        3.88         123   False  
4       1.239       8.1        1.1        3.31         112   False

In [12]:
# label encoding to one hot encode the League for neural network
label_encoder.fit(mlb_df['Lg'])
encoded_lg = label_encoder.transform(mlb_df['Lg'])
encoded_lg

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,

In [17]:
# one hot encode
from keras.utils import to_categorical


one_hot_lg = to_categorical(encoded_lg)
one_hot_lg.shape

(630, 2)

In [18]:
# need to add one hot encode arrays to the dataframe. or can i just do a True/False or 1/0??
mlb_df['Lg'] = one_hot_lg
mlb_df.head()

Year-Tm  Year   Tm   Lg   W-L%  R/G-hit  HR-hit  RBI-hit  SB-hit  BB-hit  \
0  2019MIN  2019  MIN  1.0  0.623     5.80     307      906      28     525   
1  2019NYY  2019  NYY  1.0  0.636     5.82     306      904      55     569   
2  2019HOU  2019  HOU  1.0  0.660     5.68     288      891      67     645   
3  2019LAD  2019  LAD  0.0  0.654     5.47     279      861      57     607   
4  2018NYY  2018  NYY  1.0  0.617     5.25     267      821      63     625   

   SO-hit  BA-hit  OBP-hit  SLG-hit  OPS-hit  LOB-hit  OPS+-hit  ERA-pitch  \
0    1334   0.270    0.338    0.494    0.832     1115       119       4.18   
1    1437   0.267    0.339    0.490    0.829     1039       117       4.31   
2    1166   0.274    0.352    0.495    0.848     1168       120       3.66   
3    1356   0.257    0.338    0.472    0.810     1124       112       3.39   
4    1421   0.249    0.329    0.451    0.781     1100       112       3.78   

   WHIP-pitch  H9-pitch  HR9-pitch  SO/W-pitch  ERA+-pitch  Winner  
0       1.304       9.0        1.2        3.24         108   False  
1       1.304       8.6        1.5        3.03         106   False  
2       1.130       7.4        1.4        3.73         127   False  
3       1.102       7.5        1.2        3.88         123   False  
4       1.239       8.1        1.1        3.31         112   False

In [7]:
data = mlb_df.values
X = data[:, 3:22]
y = data[:, 23]

In [8]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

In [14]:
encoded_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [15]:
from keras.utils import to_categorical

# Step 2: One-hot encoding
one_hot_y = to_categorical(encoded_y)
one_hot_y

Using TensorFlow backend.
C:\Users\Owner\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Owner\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Owner\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Owner\anaconda3\envs\Py

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)